### ISSUE TITLE
Problema com transações de cartão de débito

### ISSUE THREAD

**Issue by mausclaffani** [DevelopersRede/erede-csharp#3]
Estamos tentando utilizar a biblioteca para pagamento em cartão de débito. Porém é retornado que a URL informada para sucesso ou failure não foi tipicada.

Segue abaixo o código utilizado para apreciação:

Dim loja As New eRede.Store("XXXXXX", "XXXXXXXXXX", eRede.Environment.Production)
        Dim transacao As New eRede.Transaction With {
            .amount = 100,
            .reference = "123098"
        }
       transacao.DebitCard("xxxxxxxxxx", "855", "03", "2023", "MAURICIO")
 
        transacao.threeDSecure = New eRede.ThreeDSecure With {
            .userAgent = "ABNT Catalogo",
            .embedded = True,
            .onFailure = "decline"
        }
        transacao.AddUrl("https://www.abntcatalogo.com.br/cielo/homologa/gtrt.aspx", "threeDSecureSuccess")
        transacao.AddUrl("https://www.abntcatalogo.com.br/cielo/homologa/gtrt.aspx", "threeDSecureFailure")
 
        Dim manager As New eRede.eRede(loja)
       Dim resposta As eRede.TransactionResponse = manager.create(transacao)

**Comment by netojoaobatista** [comment]
@mausclaffani, por favor, faça um `git pull` para atualizar seu código aí. Feito isso, teste com o seguinte código:

```csharp
const string pv = "PV";
const string token = "TOKEN";
var environment = Environment.Sandbox();

var store = new Store(pv, token, environment);
var transaction = new Transaction
{
    amount = 20,
    reference = "pedido" + new Random().Next(200, 10000)
}.DebitCard(
    "2223000148400010",
    "123",
    "12",
    "2020",
    "Fulano de tal"
);

transaction.AddUrl("http://example.org/success", Url.THREE_D_SECURE_SUCCESS);
transaction.AddUrl("http://example.org/failure", Url.THREE_D_SECURE_FAILURE);

var response = new eRede.eRede(store).create(transaction);

if (response.returnCode == "220")
{
    Console.Write(response.threeDSecure.url);
}
```
