### ISSUE TITLE
Erro ao executar o sample

### ISSUE THREAD

**Issue by 1dmiranda** [DevelopersRede/erede-csharp#4]
Irei fazer uma integração com o eRede utilizando a library, fui fazer testes no Sample que está anexado e retornou o seguinte erro.

![erro e-rede](https://user-images.githubusercontent.com/36938022/64449817-1f0c4080-d0b7-11e9-97b6-caf5ea333e18.jpg)

**Comment by jfobaltazar** [comment]
@1dmiranda 
Verifique se o PV e o Password que vc passou estão corretos.
Você criou uma conta de desenvolvedor e criou sua loja?

Criando sua loja irá gerar um PV e password, na qual vc precisa inserir na variavel no top desse exemplo.

Segue link de cadastro.
https://www.userede.com.br/desenvolvedores/pt/cadastro

**Comment by 1dmiranda** [comment]
Já tentei cadastrar na plataforma mas toda vez que clico no e-mail pra validar ocorre um erro.
![image](https://user-images.githubusercontent.com/36938022/64881967-7750be80-d632-11e9-9c39-7b84c0972333.png)
